In [1]:
import numpy as np

In [5]:
#Creating NumPy Arrays 
my_list = [1,2,3]
my_list

[1, 2, 3]

In [7]:
np.array(my_list)

array([1, 2, 3])

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#Built-in Methods
# There are lots of built-in ways to generate Arrays
np.arange(0,10)
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [21]:
# zeros and ones
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
# linspace
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [31]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [33]:
# eye
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
# Random
np.random.rand(3)

array([0.65676931, 0.8200599 , 0.21853061])

In [37]:
np.random.rand(3,5)

array([[0.023725  , 0.56207595, 0.13820578, 0.29958387, 0.81138814],
       [0.20339168, 0.8589399 , 0.16733087, 0.85357253, 0.85385872],
       [0.90322317, 0.02289736, 0.70046327, 0.74887521, 0.88760816]])

In [39]:
#randn(standard normal distribution)
np.random.randn(5,5)

array([[ 4.15539166e-01,  1.66444605e+00,  5.30813883e-01,
        -2.98789184e-01, -4.74336195e-01],
       [-1.03788912e+00,  6.10980338e-01, -6.98347869e-04,
         6.75705457e-02, -4.06146931e-01],
       [ 9.61979215e-01,  1.70116614e+00, -2.85947937e-01,
        -1.31806512e+00,  1.23870762e+00],
       [ 1.53961086e-01, -1.56260081e+00, -5.84231318e-01,
         4.58919146e-01,  1.76374215e-01],
       [-1.00564145e+00, -8.59890325e-01,  7.06479016e-01,
         2.14587704e+00,  8.25241460e-01]])

In [41]:
# randint
np.random.randint(1,10)

7

In [43]:
np.random.randint(1,100,10)

array([24, 47, 92, 24,  5, 84,  5, 29, 40, 70])

In [45]:
# Array Attributes and Methods
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)

In [47]:
arr,ranarr

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]),
 array([ 7, 29, 13, 25,  6, 15, 34,  1, 30, 11]))

In [49]:
# Reshape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
# max,min,argmax,argmin
ranarr

array([ 7, 29, 13, 25,  6, 15, 34,  1, 30, 11])

In [53]:
ranarr.max()

34

In [59]:
ranarr.argmax()

6

In [66]:
ranarr.min()

1

In [68]:
ranarr.argmin()

7

In [70]:
# Shape
#vector
arr.shape

(25,)

In [74]:
#the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [76]:
arr.reshape(1,25).shape

(1, 25)

In [78]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [80]:
arr.reshape(25,1).shape

(25, 1)

In [82]:
arr.dtype

dtype('int32')

In [94]:
# NumPy Indexing and Selection
arr1=np.arange(0,20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [120]:
# Bracket Indexing and Selection
arr1[1:5]

array([1, 2, 3, 4])

In [122]:
# Broadcasting
arr1[0:5]

array([0, 1, 2, 3, 4])

In [135]:
slice_arr=arr1[10:16]
slice_arr


array([10, 11, 12, 13, 14, 15])

In [137]:
slice_arr[:]=99

In [139]:
slice_arr


array([99, 99, 99, 99, 99, 99])

In [143]:
arr1# Data is not copied, it's a view of the original array! 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 99, 99, 99, 99, 99, 99, 16,
       17, 18, 19])

In [145]:
# Indexing a 2D array (matrices)
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [153]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [157]:
# Fancy Indexing
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [161]:
for i in range(10):
    arr2d[i]=i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [177]:
arr_length = arr2d.shape[1]
arr_length 

10

In [181]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [199]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [201]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [203]:
bool_arr =arr>4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [223]:
# NumPy Operations
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [225]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [213]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [215]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [217]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [219]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [221]:
arr**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [227]:
# Universal Array Functions
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [229]:
#Calcualting exponential (e^)
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [231]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [233]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [235]:
# NumPy Exercises
# 1.Create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [239]:
# 2.Create an array of 10 ones
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [243]:
# 3.Create an array of 10 fives
np.ones(10,dtype=int)+4

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [249]:
# 4.Create an array of the integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [253]:
# 5.Create an array of all the even integers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [257]:
# 6.Create a 3x3 matrix with values ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [261]:
# 7.Create a 3x3 identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [263]:
# 8.Use NumPy to generate a random number between 0 and 1
np.random.rand()

0.79456259249535

In [271]:
# 9.Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)

array([ 0.70286928, -0.2741875 , -0.3976356 , -0.54824163,  0.35923414,
        1.55043146,  1.16220265,  0.50596735,  2.07316677, -0.22866996,
       -1.62653367,  0.86281863,  0.95655778,  0.55838054,  0.18119201,
        0.46647229, -1.11237779, -1.34371653,  1.60725068,  0.65574315,
        0.92695299,  0.34926872, -0.25358407,  0.56158583,  1.07387796])

In [279]:
# 10.Create the following matrix:
np.linspace(0.01, 1.0, 100).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [281]:
# 11.Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [283]:
# 12.Numpy Indexing and Selection
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [285]:
# 13.array([[12, 13, 14, 15],
       # [17, 18, 19, 20],
       # [22, 23, 24, 25]])
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [287]:
arr[3,4]

20

In [289]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [291]:
arr[4:,0:]

array([[21, 22, 23, 24, 25]])

In [295]:
arr[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [305]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [307]:
np.sum(arr)

325

In [315]:
# Get the standard deviation of the values in mat
np.std(arr)

7.211102550927978

In [321]:
# Get the sum of all the columns in mat
np.sum(arr[0:1,0:5])

15

In [323]:
arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [332]:
arr1=np.array([55,60,65,70,75])

In [344]:
arr1

array([55, 60, 65, 70, 75])